name: AdbeInstallTests

on:
  push:
    branches: [master, main]
    paths:
      - 'Makefile'
      - 'requirements.txt'
      - 'setup.py'
      - 'setup.cfg'
      - 'adbe/*'
      - 'tests/*'
      - '.github/workflows/adbe-installtests.yml'
  pull_request:
    branches: [master, main]
    paths:
      - 'Makefile'
      - 'requirements.txt'
      - 'setup.py'
      - 'setup.cfg'
      - 'adbe/*'
      - 'tests/*'
      - '.github/workflows/adbe-installtests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testOnAndroidDevice:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [21]
        target: [default]  # Other option: google_apis
        arch: [x86_64]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Ref: https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: Nexus 6
          script: |
            python3 -m pip install --upgrade pip
            python3 -m pip install --user -r requirements.txt
            touch docs/README.rst
            make build
            python3 -m pip install --user dist/*.whl
            set -v
            # Ref: https://stackoverflow.com/a/62151306/434196
            ls $(python3 -m site --user-base)
            ls $(python3 -m site --user-base)/bin
            ls $(python3 -m site --user-base)/bin/adbe
            $(python3 -m site --user-base)/bin/adbe --version
            PATH=$PATH:$(python3 -m site --user-base)/bin adbe --version  # Verify adbe is installed
            PATH=$PATH:$(python3 -m site --user-base)/bin make test_python3_installation
