name: AdbeUnitTests

on:
  push:
    branches: [master, main]
    paths:
      - 'Makefile'
      - 'requirements.txt'
      - 'adbe/*'
      - 'tests/*'
      - '.github/workflows/adbe-unittests.yml'
  pull_request:
    branches: [master, main]
    paths:
      - 'Makefile'
      - 'requirements.txt'
      - 'adbe/*'
      - 'tests/*'
      - '.github/workflows/adbe-unittests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittestsApi21And26:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        api-level: [21, 26]
        target: [default]  # Other option: google_apis

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          target: ${{ matrix.target }}
          script: |
            python3 -m pip install --upgrade pip
            python3 -m pip install --user -r requirements.txt
            make test_python3
