name: AdbeInstallTests

on: [push]

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 15
    strategy:
      matrix:
        api-level: [21]
        target: [default]  # Other option: google_apis
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: |
            python3 -m pip install --upgrade pip
            python3 -m pip install --user -r requirements.txt
            touch docs/README.rst
            make build
            sudo python3 -m pip install -e .
            ls /usr
            ls /usr/local
            ls /usr/local/bin
            /usr/local/bin/adbe --version  # Verify adbe is installed
            alias adbe=/usr/local/bin/adbe
            adbe --version  # Verify adbe is installed
            make test_python3_installation
