name: AdbeUnitTests

on:
  workflow_dispatch:
  push:
    branches: [master, main]
    paths:
      - "Makefile"
      - "pyproject.toml"
      - "uv.lock"
      - "adbe/*"
      - "tests/*"
      - ".github/workflows/adbe-unittests.yml"
  pull_request:
    branches: [master, main]
    paths:
      - "Makefile"
      - "pyproject.toml"
      - "uv.lock"
      - "adbe/*"
      - "tests/*"
      - ".github/workflows/adbe-unittests.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittestsApi21And26:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      max-parallel: 2
      matrix:
        api-level: [21, 26]
        target: [default]  # Other option: google_apis

    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Ref: https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
      - name: Enable KVM
        # For some weird reason, if KVM is enabled then emulator times out on API 26!
        # Ref: https://github.com/ashishb/adb-enhanced/actions/runs/8591215419/job/23539714583?pr=242
        if: matrix.api-level != 26
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -no-metrics -camera-back none
          disable-animations: true
          target: ${{ matrix.target }}
          script: make test_python3
