name: Install adb-enhanced via homebrew

on:
  schedule:
    - cron: "0 0 * * 0"  # Sunday midnight UTC
  workflow_dispatch:
  push:
    branches: [master, main]
    paths:
      - ".github/workflows/install-adb-enhanced-from-homebrew.yml"
  pull_request:
    branches: [master, main]
    paths:
      - ".github/workflows/install-adb-enhanced-from-homebrew.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  installHomebrew:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install adb-enhanced from homebrew
        run: |
          HOMEBREW_NO_INSTALL_CLEANUP=true brew install --verbose adb-enhanced || echo "brew install returned non-zero exit code"
          adbe --version
          brew uninstall adb-enhanced
